<?php
	session_start();
	if(!isset($_SESSION['loginUser'])){
		header("Location:index.php");
	}else{
		if($_SESSION['loginUser']=='afra'){
			header("Location:adminHome.php");
		}
		else{
			header("Location:customerHome.php");
		}
	}
?>